const PRIMARY_COLOR = "#FF4D4D";
const SECONDARY_COLOR = "#FF8364";
const SUPPLEMENT_COLOR = "#FDB87D";
const LIGHT_COLOR = "#FFE8D5";

export { PRIMARY_COLOR, SECONDARY_COLOR, SUPPLEMENT_COLOR, LIGHT_COLOR };
